version: "3.8"

volumes: 
    rabbitmq_data:
    
services: 


  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: polarice-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  #################################################
  # Activity Log: The Activity Log microservice (FIX TELE LOGGING SERVICE LATER FIRST)
  #################################################
  activity_log:
    # build:
    #   context: ./server
    #   dockerfile: activity_log.Dockerfile
    image: rudeous/polarice:activity_log
    container_name: activity_log
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
  
  ###################################
  # Error: The Error microservice
  ###################################
  error_log:
    # build:
    #   context: ./server
    #   dockerfile: error_log.Dockerfile
    image: rudeous/polarice:error_log
    container_name: error_log
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # roomController image
  ###############################################
  room-controller:
    # build:
    #   context: ./server
    #   dockerfile: ./roomController.Dockerfile
    image: rudeous/polarice:room-controller
    container_name: roomController
    depends_on:
      - rabbitmq
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: roomController
      rabbit_host: rabbitmq
      rabbit_port: 5672 
      firebase_apiKey: AIzaSyAr-xDgcEBJxaCIQgyN5CXGHC2NWnbXW54
      firebase_authDomain: polarice-95e3e.firebaseapp.com
      firebase_databaseURL: https://polarice-95e3e-default-rtdb.firebase
      firebase_projectId: polarice-95e3e
      firebase_storageBucket: polarice-95e3e.appspot.com
      firebase_messagingSenderId: 1088055969732
      firebase_appId: 1:1088055969732:web:37c08c0cedebacffc28691
      firebase_storageBucket: gs://polarice-95e3e.appspot.com/
      GOOGLE_CLIENT_ID: 247832333935-utbjk5kkg0er0nic8ava6l2nrsu7f2m0.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 3NrnnWhhUUoaJR7pSgeCZWyB
    ports:
      - "5000:5000"


  #################################################
  # Room image
  #################################################
  room: 
    # build: 
    #   context: ./server
    #   dockerfile: ./Room.Dockerfile
    image: rudeous/polarice:room
    container_name: Room
    restart: always
    environment: 
      PYTHONBUFFERED: 1
      FLASK_APP: Room
    ports:
      - "5004:5004"


  ###############################################
  # model image
  ###############################################
  model:
    # build:
    #   context: ./server
    #   dockerfile: ./model.Dockerfile
    image: rudeous/polarice:model
    container_name: model
    depends_on:
      - rabbitmq
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: model
      rabbit_host: rabbitmq
      rabbit_port: 5672
    ports:
      - "5003:5003"

  ###############################################
  # stripe_test image
  ###############################################
  stripe_test:
    # build:
    #   context: ./server/flask_stripe
    #   dockerfile: ./stripe_test.Dockerfile
      # args:
      #   # FOO: ${FOO}
      #   GOOGLE_CLIENT_ID: "247832333935-utbjk5kkg0er0nic8ava6l2nrsu7f2m0.apps.googleusercontent.com"
      #   GOOGLE_CLIENT_SECRET: "3NrnnWhhUUoaJR7pSgeCZWyB"
    image: rudeous/polarice:stripe_test
    container_name: stripe_test
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: stripe_test
      STRIPE_SECRET_KEY: sk_test_51IZDccAbp1R4NDVpwiDNokHhGocrvJcS5Hr81HRqA77ElouL0M1rPyqa3gvaR8vx2woadGWc5LXDe12nBdlEnlEN00xtFh2uWd
      STRIPE_PUBLISHABLE_KEY: pk_test_51IZDccAbp1R4NDVpQtpOgEjkhND5iAIpLVieMS1HKByCl61ed6xNoMGLy8f5VdMgZwDngRIkeXzxrb5wAxzrwqAi00K6OPe4Ke
      success_url: 'https://127.0.0.1:5000/create/callback'
    ports:
      - "5011:5011"


  ###############################################
  # twitter image
  ###############################################
  twitter:
    # build:
    #   context: ./server
    #   dockerfile: ./twitter.Dockerfile
    image: rudeous/polarice:twitter
    container_name: twitter
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: twitter
      twitter_consumer_key: 6iljKEF7roiA5zWsFTViL1mRy
      twitter_consumer_secret: oB3qvpOlubGNwxEe1YcSKUKEeYkqfvUUO7EabTCQzbzgS1vm
      twitter_access_token: 1373634574488530946-wqGBAKUYqfnX3bsrCcP5glIHTMuUUV
      twitter_access_secret: LxCzPSKt3Ks0NALFkN1gV9txgmO7lhbex9ZYzq5ldjzz2
    ports:
      - "5013:5013"
  

  ###############################################
  # gameController image
  ###############################################
  game-controller:
    # build:
    #   context: ./server
    #   dockerfile: ./gameController.Dockerfile
    image: rudeous/polarice:game-controller
    container_name: gameController
    depends_on:
      - room
      - game
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: gameController
    ports:
      - "5001:5001"


  ###############################################
  # Game image
  ###############################################
  game:
    # build:
    #   context: ./server
    #   dockerfile: ./Game.Dockerfile
    image: rudeous/polarice:game
    container_name: Game
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: game
    ports:
      - "5002:5002"

    
  ###############################################
  # matching image
  ###############################################
  matching:
    # build:
    #   context: ./server
    #   dockerfile: ./matching.Dockerfile
    image: rudeous/polarice:matching
    container_name: matching
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: matching
    ports:
      - "5005:5005"

  
  ###############################################
  # tele_log image
  ###############################################
  tele_log:
    # build:
    #   context: ./server
    #   dockerfile: ./tele_log.Dockerfile
    image: rudeous/polarice:tele_log
    container_name: tele_log
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: tele_log
      tele_bot_token: 1569222163:AAG0_ajeXRNWghIyKQzkwDJ6HRjhKZBADRQ
    ports:
      - "5012:5012"



  #################################################
  # Frontend vue application
  #################################################
  # frontend: 
  #   build:
  #     context: ./client
  #     command: npm run serve
  #     dockerfile: ./frontend.Dockerfile

  #   image: rudeous/frontend:polarice
  #   ports:
  #     - "8080:8080"
  #   volumes:      
  #     - .:/usr/app/
  #     - /usr/app/node_modules
