version: "3.8"

volumes:
  rabbitmq_data:

# web:
#   env_file:
#     - .env

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  activity_log:
    build:
      context: ./
      dockerfile: activity_log.Dockerfile
    image: yashgadodia/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # roomController image
  ###############################################
  polarice:
    build:
      context: .
      dockerfile: ./roomcontroller.Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: roomController
    ports:
      - "127.0.0.1:5000:5000"

# network: 